name: Caller workflow

on:
  workflow_dispatch:

jobs:
  jobA:
    uses: DefaultOrg24/GH-Actions-Training/.github/workflows/reusable_workflow.yml@main

  jobB:
    needs: jobA
    runs-on: windows-latest
    steps:      
      - name: Build
        run: echo "Building the application..."
